Messages:
   NoPermission: "&cYou don't have permission to use this command."
   Usage: "&8[&3pws&8] &7Usage: /setspawn."
   SpawnSet: "&8[&3pws&8] &aSpawnPoint set for the world &f%world%."
   SpawnTp: "&8[&3pws&8] &aYou have been teleported to spawn."
   No-SpawnSet: "&8[&3pws&8] &cError: Un-able to teleport to spawn, No Spawnpoint set."
   Spawn-Other: "&8[&3pws&8] &aYou have teleported &f%target% &ato spawn."
   Player-Not-Online: "&8[&3pws&8] &f%target% &cis not online."
   Reload-Usage: "&8[&3pws&8] &7Usage: /pws reload"
   Reload-Config: "&8[&3pws&8] &aConfiguration File has been reloaded."